Update use cases in DG
AY2021S1-CS2103T-T13-2/tp pull request #253
Opened 2020-11-08 09:51 UTC by joshtyf

Updated the use cases in the DG

2020-11-08 14:28 UTC, GilbertTan19 requested changes
OVerall, LTM! Just a small change needed

2020-11-08 14:28 UTC, GilbertTan19 commented on docs/DeveloperGuide.md
> +**Use case: UC116 - Export flashcard data file**
I think there is a typo here?

2020-11-08 15:16 UTC, joshtyf commented on docs/DeveloperGuide.md
> +**Use case: UC116 - Export flashcard data file**
Oh oops. Okay, will change it

2020-11-09 00:15 UTC, GilbertTan19 approved these changes
LGTM!

2020-11-09 00:17 UTC, merged