Add organisation related use cases #24
AY2021S1-CS2103T-T13-2/tp pull request #38
Opened 2020-09-23 07:22 UTC by joshtyf

Added organisation related use cases to the DG

2020-09-23 08:26 UTC, josiahkhoo requested changes
LGTM, just a few typos 👍

2020-09-23 08:26 UTC, josiahkhoo commented on docs/DeveloperGuide.md
> +5. QuickCache adds the tags to the flashcard.
I think this should be number 6

2020-09-23 08:26 UTC, josiahkhoo commented on docs/DeveloperGuide.md
> +	*
Empty point

2020-09-24 06:34 UTC, joshtyf commented on docs/DeveloperGuide.md
> +5. QuickCache adds the tags to the flashcard.
will fix!

2020-09-24 06:34 UTC, joshtyf commented on docs/DeveloperGuide.md
> +	*
fixed in the latest commit!

2020-09-24 08:04 UTC, josiahkhoo approved these changes
Looks good, thanks Josh!

2020-09-24 15:34 UTC, merged